name:                lww-hs
version:             0.1.0.0
github:              "jartur/lww-hs"
license:             BSD3
author:              "Ilya Pavlenkov"
maintainer:          "j@rtur.me"
copyright:           "Merely.Works"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jartur/lww-hs#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5.10.2
- QuickCheck >= 2.10.1
- scotty >= 0.11.1
- aeson 
- stm
- mtl
- transformers
- persistent
- persistent-sqlite
- persistent-template
- monad-logger
- cmdargs
- text
- http-types
- data-default
- bytestring
- time

library:
  source-dirs: src

executables:
  lww-hs-app:
    main:             Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lww-hs

tests:
  lww-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lww-hs
